<?php

namespace App\DTOs;
class AnalyseChimiqueDTO {
    public function __construct(
        public ?int $id,
        public float $Displacement,
        public float $Alite_CS,
        public float $R_wp,
        public float $FA_Sum,
        public float $Clinker,
        public float $fCaO,
        public float $Alite_Sum,
        public float $Belite_Sum,
        public float $Alum_Sum,
        public float $Ferrite,
        public float $Gypse,
        public float $CALCAIRE,
        public float $SO3,
        public float $Mullite,
        public float $Quartz,
        public float $Magnetite,
        public float $Hematite,
        public float $Flyash_amorph,
        public float $Alite_M1,
        public float $Alite_M3,
        public float $Fraction_M1,
        public float $R_exp,
        public float $Alite_PO,
        public float $Belite_alpha,
        public float $Belite_alpha_H,
        public float $Belite_beta,
        public float $Belite_gamma,
        public float $Alum_cubic,
        public float $Alum_ortho,
        public float $Lime,
        public float $Portlandite,
        public float $Periclase,
        public float $Arcanite,
        public float $Aphthitalite,
        public float $Langbeinite,
        public float $Gypsum,
        public float $Hemi_dHydrate,
        public float $Anhydrite,
        public float $SO3,
        public float $CO2,
        public float $Syngenite,
        public float $Calcite,
        public float $Dolomite,
        public int $analyse_id,
    ) {}

    public static function fromAdd(array $data): self
    {
        return new self(
            id: null,
        'Displacement',
        'Alite_CS',
        'R_wp',
        'FA_Sum',
        'Clinker',
        'fCaO',
        'Alite_Sum',
        'Belite_Sum',
        'Alum_Sum',
        'Ferrite',
        'Gypse',
        'CALCAIRE',
        'SO3',
        'Mullite',
        'Quartz',
        'Magnetite',
        'Hematite',
        'Flyash_amorph',
        'Alite_M1',
        'Alite_M3',
        'Fraction_M1',
        'R_exp',
        'Alite_PO',
        'Belite_alpha',
        'Belite_alpha_H',
        'Belite_beta',
        'Belite_gamma',
        'Alum_cubic',
        'Alum_ortho',
        'Lime',
        'Portlandite',
        'Periclase',
        'Arcanite',
        'Aphthitalite',
        'Langbeinite',
        'Gypsum',
        'Hemi-Hydrate',
        'Anhydrite',
        'SO3',
        'CO2',
        'Syngenite',
        'Calcite',
        'Dolomite',
            analyse_id: $data['analyse_id'],
        );
    }

    
    
    
}
