<?php

namespace App\DTOs;
class XrdDTO {
    public function __construct(
        public ?int $id,
        public float $Displacement,
        public float $Alite_CS,
        public float $R_wp,
        public float $FA_Sum,
        public float $Clinker,
        public float $fCaO_XRD, 
        public float $Alite_Sum,
        public float $Belite_Sum,
        public float $Alum_Sum,
        public float $Ferrite,
        public float $Gypse,
        public float $CALCAIRE,
        public float $SO3,
        public float $Mullite,
        public float $Quartz,
        public float $Magnetite,
        public float $Hematite,
        public float $Flyash_amorph,
        public float $Alite_M1,
        public float $Alite_M3,
        public float $Fraction_M1,
        public float $R_exp,
        public float $Alite_PO,
        public float $Belite_alpha,
        public float $Belite_alpha_H,
        public float $Belite_beta,
        public float $Belite_gamma,
        public float $Alum_cubic,
        public float $Alum_ortho,
        public float $Lime,
        public float $Portlandite,
        public float $Periclase,
        public float $Arcanite,
        public float $Aphthitalite,
        public float $Langbeinite,
        public float $Gypsum,
        public float $Hemi_Hydrate,
        public float $Anhydrite,
        public float $SO3_XRD,
        public float $CO2_XRD,
        public float $Syngenite,
        public float $Calcite,
        public float $Dolomite,
        public int $analyse_id,
    ) {}

    public static function fromAdd(array $data): self
    {
        return new self(
        id: null,
        Displacement: $data['Displacement'] ?? 0,
        Alite_CS: $data['Alite_CS'] ?? 0,
        R_wp: $data['R_wp'] ?? 0,
        FA_Sum: $data['FA_Sum'] ?? 0,
        Clinker: $data['Clinker'] ?? 0,
        fCaO_XRD: $data['fCaO_XRD'] ?? 0,
        Alite_Sum: $data['Alite_Sum'] ?? 0,
        Belite_Sum: $data['Belite_Sum'] ?? 0,
        Alum_Sum: $data['Alum_Sum'] ?? 0,
        Ferrite: $data['Ferrite'] ?? 0,
        Gypse: $data['Gypse'] ?? 0,
        CALCAIRE: $data['CALCAIRE'] ?? 0,
        SO3: $data['SO3'] ?? 0,
        Mullite: $data['Mullite'] ?? 0,
        Quartz: $data['Quartz'] ?? 0,
        Magnetite: $data['Magnetite'] ?? 0,
        Hematite: $data['Hematite'] ?? 0,
        Flyash_amorph: $data['Flyash_amorph'] ?? 0,
        Alite_M1: $data['Alite_M1'] ?? 0,
        Alite_M3: $data['Alite_M3'] ?? 0,
        Fraction_M1: $data['Fraction_M1'] ?? 0,
        R_exp: $data['R_exp'] ?? 0,
        Alite_PO: $data['Alite_PO'] ?? 0,
        Belite_alpha: $data['Belite_alpha'] ?? 0,
        Belite_alpha_H: $data['Belite_alpha_H'] ?? 0,
        Belite_beta: $data['Belite_beta'] ?? 0,
        Belite_gamma: $data['Belite_gamma'] ?? 0,
        Alum_cubic: $data['Alum_cubic'] ?? 0,
        Alum_ortho: $data['Alum_ortho'] ?? 0,
        Lime: $data['Lime'] ?? 0,
        Portlandite: $data['Portlandite'] ?? 0,
        Periclase: $data['Periclase'] ?? 0,
        Arcanite: $data['Arcanite'] ?? 0,
        Aphthitalite: $data['Aphthitalite'] ?? 0,
        Langbeinite: $data['Langbeinite'] ?? 0,
        Gypsum: $data['Gypsum'] ?? 0,
        Hemi_Hydrate: $data['Hemi_Hydrate'] ?? 0,
        Anhydrite: $data['Anhydrite'] ?? 0,
        SO3_XRD: $data['SO3_XRD'] ?? 0,
        CO2_XRD: $data['CO2_XRD'] ?? 0,
        Syngenite: $data['Syngenite'] ?? 0,
        Calcite: $data['Calcite'] ?? 0,
        Dolomite: $data['Dolomite'] ?? 0,
        analyse_id: $data['analyse_id'],
        );
    }

    
    
    
}
